version: '3.0'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=hacker_news
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1] 0.0.0.0 146.148.109.133
    depends_on:
      - redis
      - db
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A hacker_news worker -B -l info
    volumes:
      - .:/usr/src/app/
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
