# Generated by Django 3.0.8 on 2020-07-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20200711_0941"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment", name="author", field=models.CharField(max_length=200),
        ),
    ]
